server:
  port: 8010

logging:
  level:
    com.zundarik: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  security:
    oauth2:
      client:
        registration:
          notification:
            provider: auth-service
            client-id: notification-client
            client-secret: notification-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:${server.port}/authorized"
            scope: user_info
        provider:
          auth-service:
            issuer-uri: "http://localhost:${server.port}"

eureka:
  client:
    enabled: false
